export const labels = {
  appTitle: "みんなで楽しくチンチロ",
  appSubtitle: "天使のチンチロリン",
  sections: {
    players: "プレイヤー",
    gameSettings: "ゲーム設定",
    rule123: "123 特別ルール",
    playerDialogTitle: "プレイヤーを設定",
  },
  fields: {
    startCups: "開始杯数",
    addPerRound: "増加杯数",
    cutOff: "無効にする出目",
    cupsUnit: "杯",
    playerCount: "人数",
    playerName: "プレイヤー",
    endCupLimit: "杯以上で終了",
  },
  actions: {
    addPlayers: "プレイヤーを設定",
    cancel: "キャンセル",
    done: "完了",
    startLoseMode: "負け残りでスタート",
    startWinMode: "勝ち抜けでスタート",
    next: "NEXT",
    backToSettings: "設定に戻る",
    playAgain: "もう一度遊ぶ",
    confirm: "はい",
    close: "OK",
  },
  resultChoices: {
    none: "出目なし",
    dice1: "1",
    dice2: "2",
    dice3: "3",
    dice4: "4",
    dice5: "5",
    dice6: "6",
    special123: "123",
    special456: "456",
    specialTriple: "ぞろ目",
    special111: "ピンゾロ",
  },
  statuses: {
    battle: "BATTLE",
    noResult: "ほぼ負け",
    scored: "出目あり",
    special123: "123",
    special456: "456",
    specialTriple: "ぞろ目",
    special111: "ピンゾロ",
    winner: "勝ち抜け",
    loser: "負け",
    continue: "継続",
    revived: "復活",
  },
  messages: {
    noPlayers: "まだプレイヤーがいません",
    confirmBackToSettings: "設定ページに戻りますか？",
    errorTitle: "エラー",
    invalidPlayerCount: "2人以上で遊べます",
    emptyPlayerName: "名前が空のプレイヤーがあります",
    duplicatePlayerName: "同じ名前のプレイヤーがあります",
    invalidNumber: "設定値は数字で入力してください",
    invalidStartCups: "開始杯数は1以上にしてください",
    invalidAddPerRound: "増加杯数は0以上にしてください",
    invalidCutOff: "無効にする出目は0から6の間にしてください",
    invalidEndCupLimit: "終了条件の杯数は1以上にしてください",
    missingGameConfig: "ゲーム設定が見つかりません。設定ページから開始してください",
  },
  overlays: {
    finish: "決着",
    nextRound: "NEXT!!",
  },
} as const;

export const textLocations = {
  appTitle: "トップページの見出し",
  appSubtitle: "トップページのサブ見出し",
  sections: "トップページ内の各セクション見出し",
  fields: "設定フォーム・ゲーム画面の項目名",
  actions: "ボタン文言",
  resultChoices: "出目選択ボタンのラベル/代替テキスト",
  statuses: "プレイヤー一覧に表示する状態名",
  messages: "入力エラー、確認ダイアログ、設定読み込み失敗時の文言",
  overlays: "ゲーム中の演出オーバーレイ文言",
} as const;
